{{- if .Values.externalSecret.enabled }}
{{- $namespace := include "news_app.namespace" . -}}
{{- $secret := .Values.externalSecret -}}
{{- $externalSecretName := default (printf "%s-config" (include "news_app.fullname" .)) $secret.name -}}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $externalSecretName }}
  namespace: {{ $namespace }}
  labels:
    {{- include "news_app.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ $secret.refreshInterval }}
  secretStoreRef:
    name: {{ $secret.secretStoreRef.name }}
    kind: {{ $secret.secretStoreRef.kind }}
  target:
    name: {{ $secret.target.name }}
    creationPolicy: {{ $secret.target.creationPolicy }}
    deletionPolicy: {{ $secret.target.deletionPolicy }}
  data:
    {{- range $secret.data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteRef.key }}
        {{- with .remoteRef.property }}
        property: {{ . }}
        {{- end }}
        {{- with .remoteRef.version }}
        version: {{ . }}
        {{- end }}
    {{- end }}
{{- end }}
